// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYvv-bm8rpyYI0XOq92oBYTeE-MRuIeYM',
    appId: '1:1040405778542:web:39aff808e02df4fb17967f',
    messagingSenderId: '1040405778542',
    projectId: 'chatapp173',
    authDomain: 'chatapp173.firebaseapp.com',
    storageBucket: 'chatapp173.appspot.com',
    measurementId: 'G-JD2MPD3W46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXZGK4q8mmMfMkvJTNIPQSuUcC1jFQmkg',
    appId: '1:1040405778542:android:ff47579ba985e67517967f',
    messagingSenderId: '1040405778542',
    projectId: 'chatapp173',
    storageBucket: 'chatapp173.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPxGU1PLZVnJRHn9zhW7VHZvoKqtWQHiM',
    appId: '1:1040405778542:ios:8a4e973370e9016c17967f',
    messagingSenderId: '1040405778542',
    projectId: 'chatapp173',
    storageBucket: 'chatapp173.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPxGU1PLZVnJRHn9zhW7VHZvoKqtWQHiM',
    appId: '1:1040405778542:ios:3900ab96f9f5d42a17967f',
    messagingSenderId: '1040405778542',
    projectId: 'chatapp173',
    storageBucket: 'chatapp173.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
